name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev libicu-dev libvterm-dev
        sudo apt-get install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake sdl2 sdl2_ttf icu4c libvterm
        brew install autoconf automake python3 libmpc mpfr gmp gawk bison flex texinfo gperf libtool patchutils zlib expat
        brew install gnu-sed --with-default-names

    - name: Build RISC-V GNU toolchain (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        git clone https://github.com/riscv/riscv-gnu-toolchain
        cd riscv-gnu-toolchain
        ./configure --prefix=/usr/local
        sudo make

    - name: Build RISC-V GNU toolchain (macOS)
      if: runner.os == 'macOS'
      run: |
        git clone https://github.com/riscv/riscv-gnu-toolchain
        cd riscv-gnu-toolchain
        ./configure --prefix=/opt/homebrew/bin
        sudo make

    - name: Configure
      run: |
        cmake . -Bbuild/ -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build/

    - name: Run Tests
      run: |
        cmake -P MakeTests.cmake
        cd build/
        ctest
