name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev libicu-dev libvterm-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake sdl2 sdl2_ttf icu4c libvterm
        brew link icu4c --force

    - name: Configure
      run: |
        cmake . -Bbuild/ -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build/

    - name: Run Tests
      run: |
        cmake -P MakeTests.cmake
        cd build/
        ctest
